export const site = {
  name: "Farrukh Saif",
  firstName: "Farrukh",
  role: "MASc researcher at the University of Waterloo",
  tagline:
    "I build biomedical imaging instruments at UW: photothermal microscopes, OCT, and the software that turns raw light into an image.",
  location: "Waterloo, ON",
  email: "syedfarrukh.saif@uwaterloo.com",
  phone: "+1 382 889 4115",
  phoneHref: "tel:+13828894115",
  socials: [
    { label: "Email", href: "mailto:syedfarrukh.saif@uwaterloo.com" },
    { label: "GitHub", href: "https://github.com/farrukh-saif" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/farrukh-saif" },
  ],
  about: {
    heading: "From the optical bench to the image.",
    lead: "Master’s researcher at the University of Waterloo, developing optical imaging systems for biomedical applications.",
    body: "At PhotoMedicine Labs, supervised by Dr. Parsin Haji Reza, I built a photothermal laser scanning microscope from the ground up: lasers, scanners, relay optics, alignment, and the Python stack that acquires and forms the image. The through-line is the same: hardware, signal, and software as one system.",
    stats: [
      { label: "Now", value: "UW" },
      { label: "Lab", value: "PhotoMedicine" },
      { label: "Degree", value: "MASc ’26" },
    ],
  },
  education: [
    {
      school: "University of Waterloo",
      degree: "Master of Applied Science, System Design Engineering",
      detail: "PhotoMedicine Labs · Dr. Parsin Haji Reza",
      when: "Expected Dec. 2026",
      where: "Waterloo, ON",
      logo: "uw" as const,
    },
    {
      school: "Middle East Technical University",
      degree: "Bachelor of Science in Computer Engineering",
      detail: "Graduated with Honors",
      when: "Jun. 2024",
      where: "Ankara, TR",
      logo: "odtu" as const,
    },
  ],
  experience: [
    {
      code: "01",
      company: "PhotoMedicine Labs",
      role: "Researcher",
      when: "Nov. 2025 - Present",
      where: "UW, ON",
      logo: "uw" as const,
      tags: ["Photothermal", "OCT", "Python", "Optics"],
      highlights: [
        "Designed and built a photothermal microscope from the ground up: lasers, galvanometer scanners, relay optics, dichroics, objectives, and optomechanics.",
        "Wrote real-time imaging software in Python for acquisition, signal extraction, image formation, and post-processing.",
        "Built a swept-source OCT system and the pipeline for B-scan reconstruction, dispersion compensation, and visualization.",
        "Developed reconstruction, signal processing, and AI-based virtual H&E staining algorithms.",
      ],
    },
    {
      code: "02",
      company: "EverPixel",
      role: "Full Stack Developer",
      when: "Mar. 2025 - Jun. 2025",
      where: "Remote",
      logo: "everpixel" as const,
      tags: ["C++", "WebAssembly", "UI"],
      highlights: [
        "Ported a C++ computer vision pipeline to WebAssembly so image processing could run in the browser.",
        "Shipped full-stack features and a responsive UI redesign for a platform with 100k+ monthly active users.",
      ],
    },
    {
      code: "03",
      company: "BrainSTEAM AR Education",
      role: "Full Stack AR Engineer",
      when: "May 2023 - Sep. 2024",
      where: "Remote",
      tags: ["Unity", "AR", "CI/CD"],
      highlights: [
        "Built an augmented reality education app in Unity with real-time object detection.",
        "Optimized rendering to raise frame rates and reduce device heat on mobile.",
        "Ran CI/CD and automated deploys to the Play Store and App Store.",
      ],
    },
    {
      code: "04",
      company: "Ülkem A.Ş.",
      role: "Machine Learning Engineer",
      when: "Jun. 2023 - Jan. 2024",
      where: "Ankara, Turkey",
      tags: ["ML", "Flutter", "Selenium"],
      highlights: [
        "Collected and curated large-scale preference datasets with Selenium and Microworkers for supervised training.",
        "Built a Flutter platform for collection, annotation, and experiment monitoring, then trained perceived image-quality models for product evaluation.",
      ],
    },
  ],
  skills: [
    {
      group: "Optics",
      items: [
        "Optical system design",
        "Spaceborne optical AIT",
        "Photothermal microscopy",
        "OCT",
        "Optical alignment",
        "Optomechanical integration",
        "Computational imaging",
        "Image reconstruction",
      ],
    },
    {
      group: "Software",
      items: ["Python", "C++", "MATLAB", "LabVIEW", "Zemax", "Unity", "Flutter"],
    },
    {
      group: "Bench",
      items: [
        "Lasers",
        "Galvo scanners",
        "Photodiodes",
        "Oscilloscopes",
        "Beam profilers",
        "Power meters",
      ],
    },
  ],
  languages: ["English", "Turkish", "Urdu"],
  interests: [
    "Weightlifting",
    "Non-fiction",
    "Rock climbing",
    "Squash",
    "Billiards",
  ],
} as const;
